---
- hosts: all
#  vars:
#    http_port: 80
#    max_clients: 200
#  remote_user: vag
  tasks:
  - name: add a list of hosts to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: "^{{ item['ip'] }}.*$"
      line: "{{ item['ip'] }}\t\t{{ item['names'] | join(' ') }}"
      state: present
    with_items:
    - ip: 192.168.123.101
      names:
      - server.ipa.example.com
    - ip: 192.168.123.102
      names:
      - replica.ipa.example.com
    - ip: 192.168.123.103
      names:
      - client.ipa.example.com
  - name: set hostname
    hostname:    
      name: "{{ inventory_hostname }}.ipa.example.com"
  - name: install updates
    yum:
      name: '*'
      state: latest
      update_cache: yes
  - name: make the base not suck
    yum:
      name: [lsof,screen,bridge-utils,rsync,net-tools,nmap-ncat,vim,telnet,bind-utils,openssl,wget,curl,openssh-clients,less,iputils,traceroute,mtr,strace,unzip,xz,git,info,mlocate,findutils,grep,gawk,diffutils,iptables,tar,sed,gnupg2,python,ethtool,iproute,acl,gzip,coreutils,bc,dmidecode,patch,util-linux,expect,ntpdate,lvm2,parted,man-db,nmap,krb5-workstation,openldap-clients,bzip2,sos,tcpdump,wireshark,setroubleshoot,pcre,yum-utils,readline,which,sudo,nss,ncurses,rsyslog,file,logrotate,tmpwatch,procps-ng,hdparm,policycoreutils,firewalld,python-firewall]
      state: latest
  - name: install project specific global packages
    yum:
      name: [ipa-client]
      state: latest

- hosts: replica,server
  tasks:
  - name: install ipa server
    yum:
      name: [ipa-server,ipa-server-dns]
      state: latest

#install the rest by hand based on need
#server
#ipa-server-install --unattended --ds-password=test1234 --admin-password=test1234 --domain=ipa.example.com --realm=IPA.EXAMPLE.COM --setup-kra --setup-dns --mkhomedir --ssh-trust-dns --auto-reverse --auto-forwarders --hostname=`hostname -f`
#replica
#ipa-replica-install --unattended --admin-password=test1234 --domain=ipa.example.com --server=server.ipa.example.com --realm=IPA.EXAMPLE.COM --hostname=`hostname -f` --principal=admin --setup-ca --setup-kra --setup-dns --mkhomedir --force-join --ssh-trust-dns --auto-reverse --auto-forwarders
#client
#ipa-client-install --unattended --principal=admin --domain=ipa.example.com --server=server.ipa.example.com --realm=IPA.EXAMPLE.COM --hostname=`hostname -f` --password=test1234 --mkhomedir --force-join --force-ntpd --ssh-trust-dns --request-cert --enable-dns-updates
